### PR TITLE
Fix paths

### PR DESCRIPTION
**Pull request by duckpuppy**
Use a new utility function to standardize all separators to be a forward slash.  Forward slashes work on all OSs.  This fixes several problems found when using malabar-mode in Windows.

This also includes some fixes from the following issue comment:
https://github.com/espenhw/malabar-mode/issues/72#issuecomment-2848686

### CODE REVIEW

**Comment by buzztaiki** [comment]
Thanks! Please wait a check and review!

**Comment by buzztaiki** [comment]
I checked this patch. It also no problem. But some problem is left on windows. I would add more changes to this patch.

**Comment by buzztaiki** [comment]
Hmm.. Merge related commits is not appeared in issue...

It is merged below
- 8e4020bbf2cd43d1eebcb071af3f208eebbcf739
- 170ea6007c74042973c0fc73fa76cc7bb80b09a0

**Comment by buzztaiki** [comment]
Path problem still exists when to resolve source jar.

**Comment by duckpuppy** [comment]
Forgive me, but I'm not sure what source jar you're talking about? The
changes I made were to the paths coming from the MavenProject
instance. I've been using my changes for a while now and, while there
are still more things to fix on Windows, I can use this mode now.
Navigation works, generating import statements works (including import
all), and compilation and test works. What's not working? Can you
provide an example that doesn't?

On Mar 26, 2012, at 4:39 PM, Taiki Sugawara
reply@reply.github.com
wrote:

**Comment by buzztaiki** [comment]
Sorry, this patch fix for completion. sourceJarForClass is used to locating artifact source jar file, and it is used to reflecting class in malabar-get-class-info.

malabar-get-class-info causes error (but is is silently) before apply this patch,

**Comment by duckpuppy** [comment]
Ok. I'll take a look at it.

On Mar 26, 2012, at 5:21 PM, Taiki Sugawara
reply@reply.github.com
wrote:

**Pull request closed without merging**
